name: vinc_kiralama
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0 # Sürüm aralığı genellikle ^3.0.0 olarak kalması daha güvenlidir

dependencies:
  flutter:
    sdk: flutter

  # İkonlar
  cupertino_icons: ^1.0.8

  # State Management & Routing
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  go_router: ^17.0.1
  
  # Network & API
  
  # Environment Variables (Gizlilik)
  flutter_dotenv: ^6.0.0

  # Storage & Utilities
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2
  google_fonts: ^6.3.3
  flutter_animate: ^4.5.2

  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  mysql1: ^0.20.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generator Runner
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true

  # ASSETS KISMI BURAYA EKLENDİ
  # Boşluklara dikkat: "assets:" 2 boşluk, "- .env" 4 boşluk içeride.
  assets:
    - .env